//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanteDB.OrmLite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SanteDB.OrmLite.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result set already has Where Clause.
        /// </summary>
        internal static string ERR_ALREADY_HAS_WHERE {
            get {
                return ResourceManager.GetString("ERR_ALREADY_HAS_WHERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is not of a compatible type.
        /// </summary>
        internal static string ERR_ARGUMENT_INCOMPATIBLE_TYPE {
            get {
                return ResourceManager.GetString("ERR_ARGUMENT_INCOMPATIBLE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Required Argument.
        /// </summary>
        internal static string ERR_ARGUMENT_NULL {
            get {
                return ResourceManager.GetString("ERR_ARGUMENT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression type {0} is not valid, expected {1}.
        /// </summary>
        internal static string ERR_INVALID_EXPRESSION_TYPE {
            get {
                return ResourceManager.GetString("ERR_INVALID_EXPRESSION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not in a state which permits this operation.
        /// </summary>
        internal static string ERR_INVALID_STATE {
            get {
                return ResourceManager.GetString("ERR_INVALID_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} is missing from application context.
        /// </summary>
        internal static string ERR_MISSING_SERVICE {
            get {
                return ResourceManager.GetString("ERR_MISSING_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence has more than one element.
        /// </summary>
        internal static string ERR_SEQUENCE_MORE_THAN_ONE {
            get {
                return ResourceManager.GetString("ERR_SEQUENCE_MORE_THAN_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence does not contain any elements.
        /// </summary>
        internal static string ERR_SEQUENCE_NO_ELEMENTS {
            get {
                return ResourceManager.GetString("ERR_SEQUENCE_NO_ELEMENTS", resourceCulture);
            }
        }
    }
}
