using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.ADO.Data.Model.Concepts;
using System;

namespace SanteDB.Persistence.Data.ADO.Data.Model.Acts
{
    /// <summary>
    /// Identifies relationships between acts
    /// </summary>
    [Table("act_rel_tbl")]
    public class DbActRelationship : DbVersionedAssociation
    {

        /// <summary>
        /// Gets or sets the source act key
        /// </summary>
        [Column("src_act_id"), ForeignKey(typeof(DbAct), nameof(DbAct.Key))]
        public override Guid SourceKey { get; set; }

        /// <summary>
        /// Gets or sets the target entity key
        /// </summary>
        [Column("trg_act_id"), ForeignKey(typeof(DbAct), nameof(DbAct.Key))]
        public Guid TargetKey { get; set; }

        /// <summary>
        /// Gets or sets the link type concept
        /// </summary>
        [Column("rel_typ_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key))]
        public Guid RelationshipTypeKey { get; set; }

        /// <summary>
        /// Gets or sets the relationship id
        /// </summary>
        [Column("rel_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }
    }
}
