using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.ADO.Data.Model.Security;
using System;
using System.Diagnostics.CodeAnalysis;

namespace SanteDB.Persistence.Data.ADO.Data.Model.Mail
{
    /// <summary>
    /// Represents an alert message.
    /// </summary>
    [Table("mail_msg_tbl")]
    [ExcludeFromCodeCoverage]
	[AssociativeTable(typeof(DbSecurityUser), typeof(DbMailMessageRcptTo))]
	public class DbMailMessage : DbNonVersionedBaseData
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="DbMailMessage"/> class.
		/// </summary>
		public DbMailMessage()
		{
			
		}

		/// <summary>
		/// Gets or sets the body of the message.
		/// </summary>
		[Column("body")]
		public string Body { get; set; }

		/// <summary>
		/// Gets or sets the alert message flags.
		/// </summary>
		[Column("flags")]
		public int Flags { get; set; }
		
		/// <summary>
		/// Gets or sets the from info of the alert message.
		/// </summary>
		[Column("from_info")]
		public string FromInfo { get; set; }

		/// <summary>
		/// Gets or sets the key of the alert message.
		/// </summary>
		[Column("mail_msg_id"), PrimaryKey, AutoGenerated]
		public override Guid Key { get; set; }

		/// <summary>
		/// Gets or sets creation time of the alert message.
		/// </summary>
		[Column("msg_utc")]
		public DateTimeOffset MessageUtc { get; set; }

		/// <summary>
		/// Gets or sets the subject of the message.
		/// </summary>
		[Column("subj")]
		public string Subject { get; set; }

		/// <summary>
		/// Gets or sets the to info of the message.
		/// </summary>
		[Column("to_info")]
		public string ToInfo { get; set; }
	}
}
