using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.ADO.Data.Model.Acts;
using SanteDB.Persistence.Data.ADO.Data.Model.Entities;
using System;
using System.Diagnostics.CodeAnalysis;

namespace SanteDB.Persistence.Data.ADO.Data.Model.DataType
{
    /// <summary>
    /// Represents an identifier
    /// </summary>
    [ExcludeFromCodeCoverage]
    public abstract class DbIdentifier : DbVersionedAssociation
    {
        /// <summary>
        /// Gets or sets the value.
        /// </summary>
        [Column("id_val")]
        public String Value
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the type identifier.
        /// </summary>
        /// <value>The type identifier.</value>
        [Column("id_typ_id"), ForeignKey(typeof(DbIdentifierType), nameof(DbIdentifierType.Key))]
        public Guid? TypeKey
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the authority identifier.
        /// </summary>
        /// <value>The authority identifier.</value>
        [Column("dmn_id"), ForeignKey(typeof(DbAssigningAuthority), nameof(DbAssigningAuthority.Key))]
        public Guid AuthorityKey
        {
            get;
            set;
        }
    }

    /// <summary>
    /// Entity identifier storage.
    /// </summary>
    [Table("ent_id_tbl")]
    [ExcludeFromCodeCoverage]
    public class DbEntityIdentifier : DbIdentifier
    {
        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [Column("ent_id_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets the source key
        /// </summary>
        [Column("ent_id"), ForeignKey(typeof(DbEntity), nameof(DbEntity.Key))]
        public override Guid SourceKey { get; set; }
    }

    /// <summary>
    /// Act identifier storage.
    /// </summary>
    [Table("act_id_tbl")]
    [ExcludeFromCodeCoverage]
    public class DbActIdentifier : DbIdentifier
    {
        /// <summary>
        /// Gets or sets the act key
        /// </summary>
        [Column("act_id_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the source key
        /// </summary>
        [Column("act_id"), ForeignKey(typeof(DbAct), nameof(DbAct.Key))]
        public override Guid SourceKey { get; set; }
    }
}