using SanteDB.OrmLite.Attributes;
using System;

namespace SanteDB.Persistence.Data.ADO.Data.Model.Concepts
{
    /// <summary>
    /// Represents concept relationships
    /// </summary>
    [Table("cd_rel_assoc_tbl")]
	public class DbConceptRelationship : DbVersionedAssociation
	{
        /// <summary>
        /// Get the identifier of the key
        /// </summary>
        [Column("cd_rel_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the relationship type identifier.
        /// </summary>
        /// <value>The relationship type identifier.</value>
        [Column("rel_typ_id"), ForeignKey(typeof(DbConceptRelationshipType), nameof(DbConceptRelationshipType.Key))]
		public Guid RelationshipTypeKey {
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the source act key
        /// </summary>
        [Column("src_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key))]
        public override Guid SourceKey { get; set; }

        /// <summary>
        /// Gets or sets the target entity key
        /// </summary>
        [Column("trg_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key))]
        public Guid TargetKey { get; set; }
    }
}

