using SanteDB.OrmLite.Attributes;
using System;
using System.Diagnostics.CodeAnalysis;

namespace SanteDB.Persistence.Data.ADO.Data.Model.Concepts
{
    /// <summary>
    /// Physical data layer implemntation of concept
    /// </summary>
    [Table("cd_tbl")]
    [ExcludeFromCodeCoverage]
    [AssociativeTable(typeof(DbConceptSet), typeof(DbConceptSetConceptAssociation))]
	public class DbConcept : DbIdentified
	{

        /// <summary>
        /// Gets or sets the code identifier
        /// </summary>
        [Column("cd_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }
    }
}

