using SanteDB.OrmLite.Attributes;
using System;
using System.Diagnostics.CodeAnalysis;

namespace SanteDB.Persistence.Data.ADO.Data.Model.Concepts
{
    /// <summary>
    /// Physical data layer implemntation of concept
    /// </summary>
    [Table("cd_tbl")]
    [ExcludeFromCodeCoverage]
    [AssociativeTable(typeof(DbConceptSet), typeof(DbConceptSetConceptAssociation))]
	public class DbConcept : DbIdentified, IDbReadonly
	{

		/// <summary>
		/// Gets or sets whether the object is a system concept or not
		/// </summary>
		[Column("is_sys")]
		public bool IsReadonly {
			get;
			set;
		}

        /// <summary>
        /// Gets or sets the code identifier
        /// </summary>
        [Column("cd_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }
    }
}

