<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Condition="'$(VersionNumber)' == ''">
		<VersionNumber>3.1-debug</VersionNumber>
	</PropertyGroup>
	<PropertyGroup>
		<TargetFrameworks>net10.0;net48;netstandard2.0</TargetFrameworks>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>SanteDB.OrmLite</PackageId>
		<Title>SanteDB.OrmLite</Title>
		<Version>$(VersionNumber)</Version>
		<Description>SanteDB Lightweight ORM Mapper</Description>
		<Authors>SanteSuite Contributors</Authors>
		<PackageTags>SanteDB</PackageTags>
		<RepositoryUrl>https://github.com/santedb/santedb-orm</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IncludeSymbols>true</IncludeSymbols>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<Product>SanteDB</Product>
		<Copyright>Copyright (C) 2015-2026 SanteSuite Contributors (See: NOTICES)</Copyright>
		<Company>SanteSuite Contributors</Company>
		<PackageIconUrl>http://santesuite.org/assets/img/logo.png</PackageIconUrl>
		<PackageProjectUrl>http://santesuite.org</PackageProjectUrl>
	</PropertyGroup>
	<Choose>
		<When Condition="$(SolutionName.Contains('-nuget'))">
			<ItemGroup>
				<PackageReference Include="SanteDB.Core.Model" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Api" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.BI" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.i18n" Version="$(VersionNumber)" />
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<ProjectReference Include="..\..\santedb-model\SanteDB.Core.Model\SanteDB.Core.Model.csproj" />
				<ProjectReference Include="..\..\santedb-api\SanteDB.Core.Api\SanteDB.Core.Api.csproj" />
				<ProjectReference Include="..\..\santedb-bis\SanteDB.BI\SanteDB.BI.csproj" />
				<ProjectReference Include="..\..\santedb-i18n\SanteDB.Core.i18n\SanteDB.Core.i18n.csproj" />
			</ItemGroup>
		</Otherwise>
	</Choose>
	<ItemGroup>
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="SQLitePCLRaw.core" Version="2.1.10" />
		<PackageReference Include="System.Data.Common" Version="4.3.0" />

	</ItemGroup>
	<ItemGroup>
		<None Include="..\SanteDB.licenseheader">
			<Link>SanteDB.licenseheader</Link>
		</None>
	</ItemGroup>
</Project>