using SanteDB.OrmLite.Attributes;
using System;

namespace SanteDB.Persistence.Data.ADO.Data.Model
{

    /// <summary>
    /// Indicates an object can be readonly
    /// </summary>
    public interface IDbReadonly
    {
        /// <summary>
        /// Gets whether the object is readonly 
        /// </summary>
        bool IsReadonly { get; }
    }

    /// <summary>
    /// Represents versioned data
    /// </summary>
    public interface IDbVersionedData : IDbBaseData
    {
        
        /// <summary>
        /// Gets or sets the version identifier
        /// </summary>
        Guid VersionKey { get; set; }

        /// <summary>
        /// Gets or sets the version sequence
        /// </summary>
        Int32? VersionSequenceId { get; set; }

        /// <summary>
        /// Gets or sets teh version of the object this replaces
        /// </summary>
        Guid? ReplacesVersionKey { get; set; }
    }

    /// <summary>
    /// Versioned Database data
    /// </summary>
    public abstract class DbVersionedData : DbBaseData, IDbVersionedData
    {
        /// <summary>
        /// Gets whether the object is readonly 
        /// </summary>
        public virtual bool IsReadonly { get; }

        /// <summary>
        /// Gets or sets the version identifier
        /// </summary>
        [AutoGenerated]
        public abstract Guid VersionKey { get; set; }

        /// <summary>
        /// Gets or sets the version sequence
        /// </summary>
        [Column("vrsn_seq_id"), AutoGenerated]
        public Int32? VersionSequenceId { get; set; }

        /// <summary>
        /// Gets or sets teh version of the object this replaces
        /// </summary>
        [Column("rplc_vrsn_id")]
        public Guid? ReplacesVersionKey { get; set; }
    }

}
