using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.ADO.Data.Model.Concepts;
using System;
using System.Diagnostics.CodeAnalysis;

namespace SanteDB.Persistence.Data.ADO.Data.Model.Entities
{
    /// <summary>
    /// Represents a relationship between two entities
    /// </summary>
    [Table("ent_rel_tbl")]
    [ExcludeFromCodeCoverage]
    public class DbEntityRelationship : DbVersionedAssociation
    {
        
        /// <summary>
        /// Gets or sets the link type concept
        /// </summary>
        [Column("rel_typ_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key)), AlwaysJoin]
        public Guid RelationshipTypeKey { get; set; }

        /// <summary>
        /// Quantity 
        /// </summary>
        [Column("qty")]
        public int? Quantity { get; set; }

        /// <summary>
        /// Gets or sets the source entity id
        /// </summary>
        [Column("src_ent_id"), ForeignKey(typeof(DbEntity), nameof(DbEntity.Key))]
        public override Guid SourceKey { get; set; }

        /// <summary>
        /// Target entity key
        /// </summary>
        [Column("trg_ent_id"), ForeignKey(typeof(DbEntity), nameof(DbEntity.Key))]
        public Guid TargetKey { get; set; }

        /// <summary>
        /// Gets or sets the entity relationship id
        /// </summary>
        [Column("ent_rel_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Strength / Confidence
        /// </summary>
        [Column("conf")]
        public double? Strength { get; set; }
    }
}
