using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.ADO.Data.Model.Concepts;
using SanteDB.Persistence.Data.ADO.Data.Model.DataType;
using System;



namespace SanteDB.Persistence.Data.ADO.Data.Model.Entities
{
    /// <summary>
    /// Represents an entity name related to an entity
    /// </summary>
    [Table("ent_name_tbl")]
	public class DbEntityName : DbEntityVersionedAssociation
    {
        [Column("name_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the use concept.
        /// </summary>
        /// <value>The use concept.</value>
        [Column("use_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key))]
		public Guid UseConceptKey {
			get;
			set;
		}
	}

    /// <summary>
    /// Represents a component of a name
    /// </summary>
    [Table("ent_name_cmp_tbl")]
    public class DbEntityNameComponent : DbGenericNameComponent
    {
        /// <summary>
        /// Gets or sets the linked name
        /// </summary>
        [Column("name_id"), ForeignKey(typeof(DbEntityName), nameof(DbEntityName.Key))]
        public override Guid SourceKey { get; set; }

        /// <summary>
        /// Value of the component
        /// </summary>
        [Column("val_seq_id"), ForeignKey(typeof(DbPhoneticValue), nameof(DbPhoneticValue.SequenceId)), AlwaysJoin]
        public override Decimal ValueSequenceId { get; set; }

        /// <summary>
        /// Auto-generated value sequence
        /// </summary>
        [Column("cmp_seq"), AutoGenerated]
        public decimal? Sequence { get; set; }
    }


}

