using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.ADO.Data.Model.Concepts;
using System;

namespace SanteDB.Persistence.Data.ADO.Data.Model.Entities
{
    /// <summary>
    /// Generic name component
    /// </summary>
    public abstract class DbGenericNameComponent : DbAssociation, IDbIdentified
    {
        /// <summary>
        /// Gets or sets the key of the component
        /// </summary>
        [Column("cmp_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the type of the component
        /// </summary>
        [Column("typ_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key))]
        public Guid? ComponentTypeKey { get; set; }

        /// <summary>
        /// Get the order that this appears in the address
        /// </summary>
        [Column("seq_id"), AutoGenerated]
        public long OrderSequence { get; set; }

        /// <summary>
        /// Gets or sets the value key
        /// </summary>
        [Column("val")]
        public virtual string Value { get; set; }
    }
}