using SanteDB.OrmLite.Attributes;
using System;
using System.Diagnostics.CodeAnalysis;

namespace SanteDB.Persistence.Data.ADO.Data.Model.Entities
{
    /// <summary>
    /// Represents a person's languages of communication
    /// </summary>
    [Table("psn_lng_tbl")]
    [ExcludeFromCodeCoverage]
    public class DbPersonLanguageCommunication : DbEntityVersionedAssociation
    {
        /// <summary>
        /// Gets or sets the language code of the communication language
        /// </summary>
        [Column("lng_cs")]
        public string LanguageCode { get; set; }

        /// <summary>
        /// Gets or sets wheter this person prefers to be contacted in this language
        /// </summary>
        [Column("pref_ind")]
        public bool IsPreferred { get; set; }

        /// <summary>
        /// Get or set the pkey
        /// </summary>
        [Column("lng_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }
    }
}
