using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.ADO.Data.Model.Concepts;
using System;

namespace SanteDB.Persistence.Data.ADO.Data.Model.Entities
{
    /// <summary>
    /// Represents the orm class for place service
    /// </summary>
    [Table("plc_svc_tbl")]
    public class DbPlaceService : DbEntityVersionedAssociation
    {

        /// <summary>
        /// Gets or sets the service schedule information
        /// </summary>
        [Column("schdl")]
        public String ServiceSchedule { get; set; }

        /// <summary>
        /// Gets or sets the service concept
        /// </summary>
        [Column("svc_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key))]
        public Guid ServiceConceptKey { get; set; }

        /// <summary>
        /// Primary key
        /// </summary>
        [Column("svc_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }
    }
}
