using SanteDB.OrmLite.Attributes;
using System;
using System.Diagnostics.CodeAnalysis;


namespace SanteDB.Persistence.Data.ADO.Data.Model.Extensibility
{
    /// <summary>
    /// Extension types
    /// </summary>
    [Table("ext_typ_tbl")]
    [ExcludeFromCodeCoverage]
	public class DbExtensionType: DbNonVersionedBaseData
	{

		/// <summary>
		/// Gets or sets the name.
		/// </summary>
		/// <value>The name.</value>
		[Column("ext_name")]
		public String Name {
			get;
			set;
		}

		/// <summary>
		/// Gets or sets the extension handler.
		/// </summary>
		/// <value>The extension handler.</value>
		[Column("hdlr_cls")]
		public String ExtensionHandler {
			get;
			set;
		}

        /// <summary>
        /// Whether the extension should be executed
        /// </summary>
        [Column("is_active"), Obsolete]
        public bool IsActive { get; set; }

        /// <summary>
        /// Extension type key
        /// </summary>
        [Column("ext_typ_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }
    }
}

