using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.ADO.Data.Model.Acts;
using SanteDB.Persistence.Data.ADO.Data.Model.Entities;
using SanteDB.Persistence.Data.ADO.Data.Model.Security;
using System;
using System.Diagnostics.CodeAnalysis;


namespace SanteDB.Persistence.Data.ADO.Data.Model.Extensibility
{
    /// <summary>
    /// Represents a simpe tag (version independent)
    /// </summary>
    [ExcludeFromCodeCoverage]
    public abstract class DbTag : DbAssociation, IDbBaseData
	{
        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [Column("tag_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Created by 
        /// </summary>
        [Column("crt_prov_id"), ForeignKey(typeof(DbSecurityProvenance), nameof(DbSecurityProvenance.Key))]
        public Guid CreatedByKey { get; set; }

        /// <summary>
        /// Creation time
        /// </summary>
        [Column("crt_utc"), AutoGenerated]
        public DateTimeOffset CreationTime { get; set; }

        /// <summary>
        /// Obsoleted by 
        /// </summary>
        [Column("obslt_prov_id"), ForeignKey(typeof(DbSecurityProvenance), nameof(DbSecurityProvenance.Key))]
        public Guid? ObsoletedByKey { get; set; }

        /// <summary>
        /// Gets or sets the obsoletion time
        /// </summary>
        [Column("obslt_utc")]
        public DateTimeOffset? ObsoletionTime { get; set; }

        /// <summary>
        /// Gets or sets the key.
        /// </summary>
        /// <value>The key.</value>
        [Column("tag_name")]
		public String TagKey {
			get;
			set;
		}

		/// <summary>
		/// Gets or sets the value.
		/// </summary>
		/// <value>The value.</value>
		[Column("tag_value")]
		public String Value {
			get;
			set;
		}

        /// <summary>
        /// Gets or sets whether obsoleted by key is specified (for undelete)
        /// </summary>
        public bool ObsoletedByKeySpecified { get; set; }

        /// <summary>
        /// Gets or sets whether obsoletion time is specified
        /// </summary>
        public bool ObsoletionTimeSpecified { get; set; }
    }

	/// <summary>
	/// Represents a tag associated with an enttiy
	/// </summary>
	[Table("ent_tag_tbl")]
    [ExcludeFromCodeCoverage]
    public class DbEntityTag : DbTag
	{

        /// <summary>
        /// Gets or sets the source.
        /// </summary>
        /// <value>The source.</value>
        [Column("ent_id"), ForeignKey(typeof(DbEntity), nameof(DbEntity.Key))]
        public override Guid SourceKey
        {
            get;
            set;
        }
    }

	/// <summary>
	/// Represents a tag associated with an act
	/// </summary>
	[Table("act_tag_tbl")]
    [ExcludeFromCodeCoverage]
    public class DbActTag : DbTag
	{
        /// <summary>
        /// Gets or sets the source.
        /// </summary>
        /// <value>The source.</value>
        [Column("act_id"), ForeignKey(typeof(DbAct), nameof(DbAct.Key))]
        public override Guid SourceKey
        {
            get;
            set;
        }
    }

}

