using SanteDB.OrmLite.Attributes;
using System;
using System.Diagnostics.CodeAnalysis;

namespace SanteDB.Persistence.Data.ADO.Data.Model.Extensibility
{
    /// <summary>
    /// Represents a database template definition
    /// </summary>
    [Table("tpl_def_tbl")]
    [ExcludeFromCodeCoverage]
    public class DbTemplateDefinition : DbBaseData
    {
        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [Column("tpl_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets the OID of the template
        /// </summary>
        [Column("oid")]
        public String Oid { get; set; }

        /// <summary>
        /// Gets the name of the template
        /// </summary>
        [Column("tpl_name")]
        public String Name { get; set; }

        /// <summary>
        /// Gets the mnemonic
        /// </summary>
        [Column("mnemonic")]
        public String Mnemonic { get; set; }

        /// <summary>
        /// Gets the mnemonic
        /// </summary>
        [Column("descr")]
        public String Description { get; set; }

    }
}
